################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonar.klauke-enterprises.com -Dsonar.projectKey=maven-project-template -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - SONAR_URL=https://sonar.klauke-enterprises.com
    - SONAR_PROJECT_KEY=theresa
    - secure: "F+sfVQ/0A4x4SMaAytSiHNuqV9jOnabOIF5/ih6vF5RpUX+/Yjav7xtE4erkEhJw0l5ahKnzT1jHumIatn66SvdiFMzdKmkxxhpqjvPR+Qke9cI2aOdyaGd9yRDMTOD0LNIYJQAMDnH6kCBxpJ4Iwc8AHNK99Z38nH3iX4VwpZVrhr44ptLEFmcEBd3xkBgSqtuIpZLpP9/UP2/JX1r2GrNWQ2g8gqIUCu4JafoMhY5fEKcaYlucEEDqJF46MWVHCX0edLYu/Fv8yxlcyHWzPx+4sJ/KkWD5yVuwsNQ3GmvxFn99LzPoMORjQHM6eN486x3cDBoEoFLdBP6u62JUH8bMiYkJ9Ze0/L3Vru+NVc5EHXSgyovX8QY7s0aoQG3Obsf8eCW54I0N+QtkiU7kTReq189AoO0yC4i5wPqiwfxkb3Udup56nWlx3AMMOLtVhIKqFLju8EtniTbFjiEY0cn92DENNsEeySvnAAT/Jc11EClQv+2PTZtztYFg148Ch8dLxvlhTv/KupbV8sl7+xl+P87sA9R6yLxhw291fJpo1eqe8/xLiYB4lpM8G45Js1Pqiuy7ib+soCqIGRkM/ilDpNKpkANwZTQre28V6t+jUVWt3WY0QDA05dRFrLfHyALAdok6LhVluVFUqKtU9gkNXhk772sMkqq/mVT5DrU="
    - secure: "Xo7DIuy5BdqaTS3HIw5gQpag+Ao3eBp9fioG6jjkgq6ZRLeekA0U+NzS5WWbLm1MScrylxsI1ANLxVV4OiUoSkGxbXThb9ZwZA7lvnn36F0ijCKITTyobKiytFcZRWLQl5JhGBpMzoPbiC92zr7pqJ27yJ7RFtWi6mNuiNyYPFEptXqbUUsEN3C1LMUBymnwUGrRow0HJVcrCWuCE8McbSIY35SrNTtwZv5/87psepxlsxxJAk7Pr91cksbRZQOoV4YlwMJgzx0TnjLtZehaqZuH741DhYClipR0syxqAaKtnCEx4tHkFrZWxXkwxk2so7WZa5wU5OOqsp64o3m2pS7RyPg5mIKj7UvF1OZoRu/K2ThLgdKzyHtlkG6slBUnDKFizlbNhtldQ1SZhkokGMkeOPoUi2eyLsJbHK9WUL093ueUaSsEjgLOwpID+McIApa5NxKc3HeQnfHzbtUhIxHKI/wXv0tDASql/Da+uzTkklnjJeUW9HW0MxTW9UzeBN1PPL40wMPn7JRDPEiA5AnsCFJ0M+YSRtL7d+hzngCJA2ifXzJlc9Oo4XZKxSrPoRzSYBoHqIEZdD9ievwtgv8JmB+oJIUc0iJHfW/WwxGKhtLFTCgfvcPSZM5hQR2WtN+3VTwSHE6dfj1Uivt0parSfUPqQUsr3vdYTOjgGNU="
    - secure: "wzazSLSsga7ErUCa1OOaQyjyO5BStSud0YCcyd4WoQf+O4rmZx4lXInbkBcqUahwN2dFRaDx7Xbr2iAHRKE3UgZOkZwg1B6541ov8jjSO8zUG5Ut/E4/s3HuvAROsdZTICTAAP0S46yrQidaof6YOyOaZXLR26xFMmO88+36Qs8ECe0fgni/ge0gYUovcgGmLf6RKxJ+yCMDYiOb1Jn4xrEWGAHp+e4PJPHxhOXNsVeQbS2uLaTSvKml+NYBvrLT8VNMZIXYBmFkyb7BzGilUW4OcqzGeghL07IddQ8HUW14DSl+1fXiZ20Txpipnzp1n+KovXnwfCvfDZEQ8CV4mxF651cXqqZ3z4EWCNIUXROORWrFh2ny5kVc7fUsLzs0NcLlQSvDKV3iKQTPYrLZuL5c/I5VWOiGPe+naOV7OxfZDBzhHWdNpGdgqlqfAbwKiKmZKHNZ113J+W0hs9ZkWrf/CrWyidLRMD5TWe/DDXiVG7xABRcuSTSVIdnj7we65/AkF1wrHdU4UiU1Rj/OKDArYs5Nyp4sVWmQ5seUx3dbE9LBrIEYbsqrDu6EpJP3uh6t49yDyTEt3iGzDV6o+OPo2/ZZxof8pNxK685+VQYEN0X/jbihdbhKFYds79UH/zMPAtcULnMmfyuYpPFzal3VG//imhZYJQaBQ38LZzU="
