################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install
  - mvn verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    ####################################
    ### SonarQube Config Credentials ###
    ####################################
    - SONAR_URL=https://sonar.klauke-enterprises.com
    - SONAR_PROJECT_KEY=theresa
    #########################
    ### Nexus Credentials ###
    #########################
    - NEXUS_USERNAME=deploy
    - secure: "V+9oxlIOIop/4APS8oXfc/ExDqukChCI6xd26CIcgclIaRm8jLixvhOCud3qx0IxI8lWJT/KjJuqeuUsDaB7qTFRQ5Y7nuHoe3cZ0j/vbsG1BPDeQ+Z3MaUTG5x1ozV6w1tQy+eOEEhTfLKAEbQhP26Jgmea2Mbat6CDO+cixyTMH4uLLgNKzEw5IxxaykGNcLcY1ObkPkYLm7I287e9wbuskeE4E5r8cP0lDmrBeZt8rVt3700Ml8PCznaxvO1R/QwdMuNNXRDisPQF60x2CamSv7wKkRV0MRZicAaGGnY6rX3wxxG6zRGDV6keC8Gq4ILMRqJueyVa0/l73dWwWrVyblrblssNSOcVLJFosOMQpjCc6MvhF06gpLzhliUOH7YDaCi5le9KF2ahkytquE7rpTQLpbqsD/OvdkpXDo/I+s/iTbbZObZx0riDDWhMWeS4JJHJknSDVQ7yrWDq6SwGeR0mozOJHU20DBMQxehP16Thc1YlK5wgypEhAMt/cnvrYUz3gtA+JvYC/iMEvYCup315f1hdEVux+HZy8AZlXpeRivW8DOV3Y/p8p0e9+OypDwIhoJoaSmsATsJR8MfbwJUf1aaDH/wndkDCi6BS39fM9IdyrtbKjMGIrD1V4pKu5b2dgnBGJWnYJtyDlUdMFrVBj5dGSpMx5O0b0W4="
