######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
- openjdk11

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###########################
### Actual Build Script ###
###########################
script:
- ./gradlew build check
- ./gradlew codeCoverageReport
- ./gradlew sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN

###################################
### Upload Code Coverage Report ###
###################################
after_success:
- bash <(curl -s https://codecov.io/bash)

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - SONAR_URL=https://sonar.klauke-enterprises.com
    - SONAR_PROJECT_KEY=theresa
    - secure: "F+sfVQ/0A4x4SMaAytSiHNuqV9jOnabOIF5/ih6vF5RpUX+/Yjav7xtE4erkEhJw0l5ahKnzT1jHumIatn66SvdiFMzdKmkxxhpqjvPR+Qke9cI2aOdyaGd9yRDMTOD0LNIYJQAMDnH6kCBxpJ4Iwc8AHNK99Z38nH3iX4VwpZVrhr44ptLEFmcEBd3xkBgSqtuIpZLpP9/UP2/JX1r2GrNWQ2g8gqIUCu4JafoMhY5fEKcaYlucEEDqJF46MWVHCX0edLYu/Fv8yxlcyHWzPx+4sJ/KkWD5yVuwsNQ3GmvxFn99LzPoMORjQHM6eN486x3cDBoEoFLdBP6u62JUH8bMiYkJ9Ze0/L3Vru+NVc5EHXSgyovX8QY7s0aoQG3Obsf8eCW54I0N+QtkiU7kTReq189AoO0yC4i5wPqiwfxkb3Udup56nWlx3AMMOLtVhIKqFLju8EtniTbFjiEY0cn92DENNsEeySvnAAT/Jc11EClQv+2PTZtztYFg148Ch8dLxvlhTv/KupbV8sl7+xl+P87sA9R6yLxhw291fJpo1eqe8/xLiYB4lpM8G45Js1Pqiuy7ib+soCqIGRkM/ilDpNKpkANwZTQre28V6t+jUVWt3WY0QDA05dRFrLfHyALAdok6LhVluVFUqKtU9gkNXhk772sMkqq/mVT5DrU="
    - secure: "Xo7DIuy5BdqaTS3HIw5gQpag+Ao3eBp9fioG6jjkgq6ZRLeekA0U+NzS5WWbLm1MScrylxsI1ANLxVV4OiUoSkGxbXThb9ZwZA7lvnn36F0ijCKITTyobKiytFcZRWLQl5JhGBpMzoPbiC92zr7pqJ27yJ7RFtWi6mNuiNyYPFEptXqbUUsEN3C1LMUBymnwUGrRow0HJVcrCWuCE8McbSIY35SrNTtwZv5/87psepxlsxxJAk7Pr91cksbRZQOoV4YlwMJgzx0TnjLtZehaqZuH741DhYClipR0syxqAaKtnCEx4tHkFrZWxXkwxk2so7WZa5wU5OOqsp64o3m2pS7RyPg5mIKj7UvF1OZoRu/K2ThLgdKzyHtlkG6slBUnDKFizlbNhtldQ1SZhkokGMkeOPoUi2eyLsJbHK9WUL093ueUaSsEjgLOwpID+McIApa5NxKc3HeQnfHzbtUhIxHKI/wXv0tDASql/Da+uzTkklnjJeUW9HW0MxTW9UzeBN1PPL40wMPn7JRDPEiA5AnsCFJ0M+YSRtL7d+hzngCJA2ifXzJlc9Oo4XZKxSrPoRzSYBoHqIEZdD9ievwtgv8JmB+oJIUc0iJHfW/WwxGKhtLFTCgfvcPSZM5hQR2WtN+3VTwSHE6dfj1Uivt0parSfUPqQUsr3vdYTOjgGNU="
    - secure: "PjiDiORIOtXW3E1nMbGxQxR80MWiFlW9sVHa3JGPF9lhedLWIjKM+d2igj9Zw5hnvp1kVqWHJ2dK6kW4hViEVFNAcYa0geH/oX4m6OOXHifmgvonN3hgJCYlwHgz2+A4EeLP2kn2lJ11JdqNA1XvYWzSpkrXwcqmuqy4/lwgOtcmBEAwdPw4c10oKFaTrrf3zEePnapEAe1xS4xT8gGnxmAR52Z2Ffun76SSzV+QRpO6qZvgyaCqp+2uJbSZzsDJdtkMSXy8UEPqsaV3o5Gtu+7ci3QKb2hfsH1aQLMlVZo7QcozioTkRzZpMSiegAPkKHvDBIcXCsRH/wpnEpxmYsTySMMsWUxe8mahdBz5QycWUUvry7G7RnIW5xoPdEiIwxASZGg8yhDUmJhCt5pfQzdaGMnplSAwrx92V7ACBtrjQrG13kkbK6xFpYuYATSsawg7Kz1+/JUDYQHCHdSQsslkwsAlh3lGdelfsJWLd2d7R93kufc2Poy0XDt3XEYoxEunQ7B9+IzR92QEossh1ZBKfI0HPOOajgvitNIaRZJZLVCkFWSbkYxyDu7gPHvRasJGfZYFUR1iw0CBvLJ5LaLdwitUmxIgQ0T3sRkwd1eI4N0tkcmwr12c4r/w3y25ftt3z/Kyud9VOkcdl/BuhaESd93B0W71yTbE0blbDmY="
